# Generated by Django 5.1 on 2024-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=80)),
                ('fname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.PositiveBigIntegerField(max_length=10)),
                ('psw', models.CharField(max_length=15)),
                ('webs', models.CharField(max_length=100)),
                ('lp', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=50)),
                ('au', models.CharField(max_length=200)),
                ('ind', models.CharField(max_length=50)),
                ('wwo', models.CharField(max_length=200)),
            ],
        ),
    ]
