# Generated by Django 5.1 on 2024-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='passphotos/'),
        ),
    ]
