# Generated by Django 5.1 on 2024-10-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_hiringseekers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringseekers',
            name='cl',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
