# Generated by Django 5.1 on 2024-10-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_hiringseekers_ld'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jt', models.CharField(max_length=300)),
                ('cn', models.CharField(max_length=200)),
                ('jl', models.CharField(max_length=150)),
                ('cl', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('jtyp', models.CharField(max_length=100)),
                ('er', models.CharField(max_length=500)),
                ('kysk', models.CharField(max_length=1000)),
                ('exp', models.PositiveIntegerField()),
                ('abtcomp', models.CharField(max_length=2000)),
                ('pos', models.PositiveIntegerField()),
                ('jd', models.CharField(max_length=5000)),
                ('jr', models.CharField(max_length=4000)),
                ('sal', models.CharField(max_length=150)),
                ('al', models.CharField(max_length=300)),
                ('ld', models.DateField(default='2025-01-01')),
            ],
        ),
    ]
