# Generated by Django 5.1.1 on 2024-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_applicantdetails_abtcomp_applicantdetails_al_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
