# Generated by Django 5.1.1 on 2024-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_applicantdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired')], default='applied', max_length=20, null=True),
        ),
    ]
