# Generated by Django 5.1.1 on 2024-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_applicantdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='status',
            field=models.CharField(default='Applied', max_length=20),
        ),
    ]
