# Generated by Django 5.1.1 on 2024-10-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_applicantdetails_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedJobs',
        ),
    ]
