# Generated by Django 5.1.4 on 2025-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_delete_appliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringseekers',
            name='applied_column',
            field=models.BooleanField(default=False),
        ),
    ]
